export const GET_ALL_BUSINESSES = 'GET_ALL_BUSINESSES'
export const GET_BUSINESS = 'GET_BUSINESS'
export const CREATE_BUSINESS = 'CREATE_BUSINESS'
export const EDIT_BUSINESS = 'EDIT_BUSINESS'
export const DELETE_BUSINESS = 'DELETE_BUSINESS'

